# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cloudfiles}
  s.version = "1.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["H. Wade Minter", "Rackspace Hosting"]
  s.date = %q{2009-10-20}
  s.description = %q{A Ruby version of the Rackspace Cloud Files API.}
  s.email = %q{wade.minter@rackspace.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "COPYING",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "cloudfiles.gemspec",
     "lib/cloudfiles.rb",
     "lib/cloudfiles/authentication.rb",
     "lib/cloudfiles/connection.rb",
     "lib/cloudfiles/container.rb",
     "lib/cloudfiles/storage_object.rb",
     "test/cf-testunit.rb",
     "test/cloudfiles_authentication_test.rb",
     "test/cloudfiles_connection_test.rb",
     "test/cloudfiles_container_test.rb",
     "test/cloudfiles_storage_object_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://www.rackspacecloud.com/cloud_hosting_products/files}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby API into Rackspace Cloud Files}
  s.test_files = [
    "test/cf-testunit.rb",
     "test/cloudfiles_authentication_test.rb",
     "test/cloudfiles_connection_test.rb",
     "test/cloudfiles_container_test.rb",
     "test/cloudfiles_storage_object_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

